name: Reproduce interpreter identification bug in prek
on:
  - workflow_dispatch
  - push

jobs:
  reproduce:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install prek
        run: pip install prek
      - name: Run prek
        run: prek run -a
